workflows:
  android-debug:
    name: Android Build
    scripts:
      - name: Build with system Gradle
        script: |
          # Удаляем битые файлы
          rm -f gradlew 2>/dev/null || true
          rm -rf gradle/wrapper 2>/dev/null || true
          
          # Используем системный Gradle
          gradle assembleDebug --stacktrace --info
          
    artifacts:
      - app/build/outputs/apk/debug/*.apk
