workflows:
  android-release:
    name: Android Build
    max_build_duration: 60
    environment:
      android_signing:
        - your_keystore_here # Нужно настроить в AppCircle
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.example.hermes" # Замени на твой package name
    scripts:
      - name: Set up environment
        script: |
          chmod +x ./gradlew 2>/dev/null || true
          
      - name: Build APK
        script: |
          ./gradlew assembleDebug
          
      - name: Build Release AAB (optional)
        script: |
          ./gradlew bundleRelease
          
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      
    publishing:
      email:
        recipients:
          - ovanes727@icloud.com
