cat > codemagic.yaml << 'EOF'
# For more options, see https://docs.codemagic.io/yaml/yaml-getting-started/

workflows:
  sample-workflow:
    name: Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      groups: []
      vars:
        MY_ENV_VAR: "some value"
    scripts:
      - name: Hello world
        script: echo "Hello world!"
    artifacts:
      - "**/*.apk"
EOF
