cat > codemagic.yaml << 'EOF'
workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore.properties # если есть
    scripts:
      - name: Setup
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          chmod +x ./gradlew
      - name: Build Debug APK
        script: |
          ./gradlew clean
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
EOF
