workflows:
  apk-only:
    name: APK Search
    scripts:
      - name: Find APK
        script: find . -name "*.apk" -type f
    artifacts:
      - "**/*.apk"
    publishing:
      email:
        recipients:
          - ovanes727@icloud.com
