cat > codemagic.yaml << 'EOF'
workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play
      android_signing:
        - keystore.properties
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up Android SDK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ndk.dir=$ANDROID_SDK_ROOT/ndk-bundle" >> local.properties
      - name: Build Debug APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - hermes727op@gmail.com
EOF
