workflows:
  android-release:
    name: Android Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Quick Build Fix
        script: |
          # 1. Дать права на gradlew (если есть)
          chmod +x ./gradlew 2>/dev/null || true
          
          # 2. Собрать ОБЫЧНУЮ (не релизную) версию
          ./gradlew assembleDebug 2>&1 | head -30
          
          # 3. Если сработало - попробовать релиз
          ./gradlew assembleRelease 2>&1 | head -50
