workflows:
  android-debug:
    name: Android Build
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.example.hermes"
    
    scripts:
      - name: Set executable permissions
        script: |
          chmod +x ./gradlew
          
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
          
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      
    publishing:
      email:
        recipients:
          - ovanes727@icloud.com
