workflows:
  android-build:  # ← ЭТО НАЗВАНИЕ ДОЛЖНО СОВПАДАТЬ С ТЕМ, ЧТО ТЫ ВЫБИРАЕШЬ В AppCircle
    name: Android Build
    max_build_duration: 60
    scripts:
      - name: Make gradlew executable
        script: |
          echo "🔧 Делаем gradlew исполняемым..."
          chmod +x gradlew
          
      - name: Build APK
        script: |
          echo "🚀 Собираем APK..."
          ./gradlew assembleDebug --stacktrace
          
      - name: Find APK
        script: |
          echo "📦 Ищем APK файлы..."
          find . -name "*.apk" -type f
          
    artifacts:
      - "**/*.apk"
      
    publishing:
      email:
        recipients:
          - ovanes727@icloud.com
