---
workflows:
  android-release:
    name: Hermes Translator Android Release
    max_build_duration: 60
    environment:
      java: 17  # Используем JDK 17 на сервере Codemagic
    scripts:
      - name: Show Java version
        script: |
          java -version
      - name: Assemble Release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk  # путь к APK внутри проекта
    publishing:
      email:
        recipients:
          - your-email@example.com  # сюда придёт уведомление о сборке и ссылка на APK
