---
workflows:
  android-release:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      vars:
        java:17
    scripts:
      - name: Show Java version
        script: |
          java -version
      - name: Assemble Release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/**/*.apk  # путь к APK, можно скорректировать под проект
    publishing:
      email:
        recipients:
          - your-email@example.com  # Если хочешь получать билд по email
