workflows:
  android-workflow:
    name: Android Build
    environment:
      groups:
        - keystore_credentials # если есть подписывание
      vars:
        PACKAGE_NAME: "com.yourpackage.name"
    scripts:
      - name: Set execute permissions
        script: chmod +x ./gradlew
      - name: Build Android app
        script: ./gradlew :app:assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - evanes727@icloud.com
