---
workflows:
  android-release:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /Users/aksel/Documents/jdk-17.0.17+10
      flutter: stable  # Если проект Flutter, можно убрать, если чистый Android
      android:
        gradle_version: 7.6  # Можно указать нужную версию Gradle
    scripts:
      - name: Show Java version
        script: |
          $JAVA_HOME/bin/java -version
      - name: Assemble Release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/**/*.apk  # путь к APK, можно скорректировать под проект
    publishing:
      email:
        recipients:
          - your-email@example.com  # Если хочешь получать билд по email
