workflows:
  android-debug:
    name: Android Build
    max_build_duration: 60
    scripts:
      - name: Build without modifications
        script: |
          echo "🚀 Сборка без изменений кода..."
          echo "Используем системный Gradle..."
          gradle assembleDebug --stacktrace
    artifacts:
      - "**/*.apk"
    publishing:
      email:
        recipients:
          - ovanes727@icloud.com
