workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.example.hermes"
    scripts:
      - name: Setup and Build with Gradle
        script: |
          echo "🔧 Настройка окружения..."
          
          # Проверяем доступные версии Gradle
          echo "Доступные версии Gradle:"
          gradle --version || true
          
          # Проверяем структуру проекта
          echo "📁 Структура проекта:"
          ls -la
          echo ""
          echo "📁 Содержимое корневой папки:"
          find . -maxdepth 2 -type f -name "*.gradle*" | head -20
          
          echo "🚀 Собираем проект используя Gradle..."
          
          # Пробуем разные команды Gradle
          if [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
            echo "📦 Найден файл build.gradle, используем gradle команду..."
            gradle assembleDebug --stacktrace --info
          elif [ -f "app/build.gradle" ] || [ -f "app/build.gradle.kts" ]; then
            echo "📦 Найден app/build.gradle, собираем из корня..."
            cd app
            gradle assembleDebug --stacktrace --info
          else
            echo "❌ Не найден build.gradle файл!"
            echo "Ищем все gradle файлы:"
            find . -name "*.gradle*" -type f
            exit 1
          fi
          
          if [ $? -eq 0 ]; then
            echo "✅ Сборка успешна!"
          else
            echo "❌ Ошибка сборки!"
            exit 1
          fi
          
      - name: Find Artifacts
        script: |
          echo "🔍 Ищем созданные APK файлы..."
          
          # Ищем во всех возможных местах
          find . -name "*.apk" -type f 2>/dev/null | while read apk; do
            echo "✅ Найден: $apk"
            ls -lh "$apk"
          done
          
          # Показываем структуру build папок
          echo ""
          echo "📁 Папки сборки:"
          find . -type d -name "build" | head -5 | while read dir; do
            echo "📂 $dir:"
            find "$dir" -name "*.apk" -type f | head -3
          done
          
    artifacts:
      - "**/build/outputs/apk/**/*.apk"
      - "**/build/outputs/**/*.apk"
      - "**/*.apk"
      
    publishing:
      email:
        recipients:
          - ovanes727@icloud.com
