cat > codemagic.yaml << 'EOF'
workflows:
  android-simple:
    name: Simple Android Build
    max_build_duration: 30
    instance_type: mac_mini
    scripts:
      - name: Setup and Build
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
EOF
