workflows:
  android-release:
    name: Android Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Install Gradle directly
        script: |
          # Установить Gradle 8.5
          wget https://services.gradle.org/distributions/gradle-8.5-bin.zip
          unzip gradle-8.5-bin.zip
          export GRADLE_HOME="$PWD/gradle-8.5"
          export PATH="$GRADLE_HOME/bin:$PATH"
          
          gradle --version
          echo "Gradle home: $GRADLE_HOME"
      
      - name: Build with installed Gradle
        script: |
          # Используем установленный Gradle
          gradle clean assembleRelease --stacktrace --no-daemon
