workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.example.hermes" # Замени на твой package name
    scripts:
      - name: Setup and Build
        script: |
          echo "🔧 Настройка окружения..."
          
          # Делаем gradlew исполняемым
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            echo "✅ gradlew сделан исполняемым"
          else
            echo "❌ gradlew не найден!"
            echo "Содержимое папки:"
            ls -la
            exit 1
          fi
          
          # Проверяем Java
          echo "Версия Java:"
          java -version
          
          echo "🚀 Собираем Debug APK..."
          ./gradlew assembleDebug --stacktrace --info
          
          if [ $? -eq 0 ]; then
            echo "✅ Сборка успешна!"
            
            # Находим и показываем все APK
            APK_FILES=$(find . -name "*.apk" -type f)
            if [ -z "$APK_FILES" ]; then
              echo "⚠️ APK файлы не найдены!"
              echo "Ищем в app/build/outputs:"
              find app/build/outputs -type f
            else
              echo "📦 Найдены APK файлы:"
              echo "$APK_FILES" | while read file; do
                echo "  - $file"
                ls -lh "$file"
              done
            fi
          else
            echo "❌ Ошибка сборки!"
            exit 1
          fi
          
      - name: Verify Build
        script: |
          echo "🔍 Проверяем результат сборки..."
          
          # Ищем APK в стандартных местах
          APK_PATHS=(
            "app/build/outputs/apk/debug"
            "app/build/outputs/apk"
            "app/build/outputs"
            "build/outputs"
          )
          
          for path in "${APK_PATHS[@]}"; do
            if [ -d "$path" ]; then
              echo "📁 Проверяем папку: $path"
              find "$path" -name "*.apk" -type f | while read apk; do
                echo "✅ Найден APK: $apk"
                echo "   Размер: $(ls -lh "$apk" | awk '{print $5}')"
                echo "   Дата: $(date -r "$apk")"
              done
            fi
          done
          
          # Ищем во всем проекте
          TOTAL_APKS=$(find . -name "*.apk" -type f | wc -l)
          echo "📊 Всего APK файлов в проекте: $TOTAL_APKS"
          
          if [ $TOTAL_APKS -eq 0 ]; then
            echo "⚠️ Внимание: APK файлы не найдены!"
            echo "Структура папки app/build:"
            find app/build -type d 2>/dev/null || echo "Папка app/build не существует"
          fi
          
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/outputs/apk/*.apk
      - app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - ovanes727@icloud.com
