workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.example.hermes"
    scripts:
      - name: Generate Gradle Wrapper
        script: |
          echo "🔧 Создаем Gradle Wrapper..."
          
          # Проверяем есть ли gradle
          if command -v gradle &> /dev/null; then
            echo "✅ Gradle найден в системе"
            
            # Создаем wrapper если его нет
            if [ ! -f "./gradlew" ]; then
              echo "📦 Создаем gradle wrapper..."
              gradle wrapper --gradle-version 8.5
              
              # Проверяем что создалось
              if [ -f "./gradlew" ]; then
                chmod +x ./gradlew
                echo "✅ Gradle Wrapper создан"
                ./gradlew --version
              else
                echo "❌ Не удалось создать gradle wrapper"
                # Пробуем вручную создать структуру
                mkdir -p gradle/wrapper
                cat > gradle/wrapper/gradle-wrapper.properties << 'EOF'
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
EOF
                echo "✅ gradle-wrapper.properties создан"
              fi
            else
              echo "✅ Gradle Wrapper уже существует"
              chmod +x ./gradlew
            fi
          else
            echo "❌ Gradle не установлен в системе"
            exit 1
          fi
          
      - name: Build with Wrapper
        script: |
          echo "🚀 Собираем проект..."
          
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug --stacktrace --info
          elif [ -f "gradlew" ]; then
            chmod +x gradlew
            ./gradlew assembleDebug --stacktrace --info
          else
            echo "❌ Gradle Wrapper не найден, используем системный gradle"
            gradle assembleDebug --stacktrace --info
          fi
          
          if [ $? -eq 0 ]; then
            echo "✅ Сборка успешна!"
          else
            echo "❌ Ошибка сборки!"
            exit 1
          fi
          
      - name: Collect Artifacts
        script: |
          echo "📦 Собираем артефакты..."
          
          APK_COUNT=$(find . -name "*.apk" -type f 2>/dev/null | wc -l)
          echo "Найдено APK файлов: $APK_COUNT"
          
          if [ $APK_COUNT -eq 0 ]; then
            echo "⚠️ APK не найдены! Структура build:"
            find . -type d -name "build" | while read dir; do
              echo "📂 $dir:"
              find "$dir" -type f | head -10
            done
          else
            find . -name "*.apk" -type f | while read apk; do
              echo "📱 $apk ($(ls -lh "$apk" | awk '{print $5}'))"
            done
          fi
          
    artifacts:
      - "**/*.apk"
      
    publishing:
      email:
        recipients:
          - ovanes727@icloud.com
